#!/usr/bin/env python3
"""Export the ExtremeCloud IQ fleet to a seed-ready JSON file.

Phase 0 reconnaissance helper (CLAUDE.md §7): dumps ``GET /devices?views=BASIC``
into the ``{"data": [...]}`` shape that ``netmon-seed --xiq`` consumes to build
the device registry. Mirrors ``tests/fixtures/xiq_devices.json``.

Read-only (§4.1): reuses the collector's :class:`XiqClient`, which issues only
GETs against the fleet endpoint and never re-auths or writes. Credentials come
from the ``[xiq]`` section of the NetMon config (``--config`` / ``$NETMON_CONF``);
the token is never printed or written into the output.

Usage::

    NETMON_CONF=/etc/netmon/netmon.conf python scripts/xiq_export.py --out xiq_devices.json
    python -m netmon.seed --xiq xiq_devices.json [--pf ...] [--sites ...]

Unlike the XIQ *collector* (``python -m netmon.collectors.xiq``), which writes
live status into ``device_state`` for devices already in the registry, this
script produces the export that *creates* the registry in the first place.

**Do not commit real output** — real hostnames/IPs are not fixtures (§4.6).
Sanitize before adding anything under ``tests/fixtures/``.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from netmon.collectors.xiq_client import BASE_URL, XiqClient, XiqError  # noqa: E402
from netmon.config import ConfigError, load_config  # noqa: E402


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Export the XIQ fleet for netmon-seed --xiq.")
    p.add_argument("--config", default=None, help="NetMon config path (default $NETMON_CONF).")
    p.add_argument("--view", default="BASIC", help="XIQ device view (default BASIC).")
    p.add_argument("--out", help="Write JSON here (default: stdout).")
    args = p.parse_args(argv)

    try:
        cfg = load_config(args.config)
    except ConfigError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    src = cfg.sources.get("xiq")
    settings = src.settings if src else {}
    token = (settings.get("api_token") or "").strip()
    base_url = (settings.get("base_url") or BASE_URL).strip()
    if not token:
        print("ERROR: [xiq] api_token is not set in the config.", file=sys.stderr)
        return 1

    try:
        client = XiqClient(token, base_url)
        rows = asyncio.run(client.get_devices(view=args.view))
    except XiqError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    payload = {
        "_meta": {
            "note": (
                "XIQ GET /devices export for netmon-seed --xiq. Generated by "
                "scripts/xiq_export.py. Not a fixture — sanitize before "
                "committing (CLAUDE.md §4.6)."
            ),
            "view": args.view,
            "base_url": base_url,
            "device_count": len(rows),
        },
        "data": rows,
    }
    rem = client.rate_limit_remaining
    print(f"XIQ devices: {len(rows)}"
          + (f"  (quota remaining: {rem})" if rem is not None else ""), file=sys.stderr)

    text = json.dumps(payload, indent=2, sort_keys=False)
    if args.out:
        Path(args.out).write_text(text + "\n")
        print(f"Wrote {args.out}", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
